"""Create all tables

Revision ID: e1f3410aa20a
Revises: cb560e8a94cc
Create Date: 2025-10-24 00:53:38.206650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1f3410aa20a'
down_revision: Union[str, Sequence[str], None] = 'cb560e8a94cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_name', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(), nullable=False),
    sa.Column('degree_type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=False),
    sa.Column('duration_months', sa.Integer(), nullable=True),
    sa.Column('tuition_fee_usd', sa.Float(), nullable=True),
    sa.Column('application_fee_usd', sa.Float(), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('min_gre', sa.Integer(), nullable=True),
    sa.Column('min_toefl', sa.Integer(), nullable=True),
    sa.Column('min_ielts', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('requirements_details', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_programs_country'), 'programs', ['country'], unique=False)
    op.create_index(op.f('ix_programs_field_of_study'), 'programs', ['field_of_study'], unique=False)
    op.create_index(op.f('ix_programs_id'), 'programs', ['id'], unique=False)
    op.create_index(op.f('ix_programs_program_name'), 'programs', ['program_name'], unique=False)
    op.create_index(op.f('ix_programs_university_name'), 'programs', ['university_name'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_name', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('applicable_programs', sa.JSON(), nullable=True),
    sa.Column('amount_usd', sa.Float(), nullable=True),
    sa.Column('coverage_type', sa.String(), nullable=True),
    sa.Column('eligible_countries', sa.JSON(), nullable=True),
    sa.Column('min_gpa', sa.Float(), nullable=True),
    sa.Column('required_tests', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('requirements', sa.Text(), nullable=True),
    sa.Column('application_process', sa.Text(), nullable=True),
    sa.Column('website_url', sa.String(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_country'), 'scholarships', ['country'], unique=False)
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_index(op.f('ix_scholarships_scholarship_name'), 'scholarships', ['scholarship_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('INTERESTED', 'APPLIED', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', name='applicationstatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['programs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_applications_id'), 'applications', ['id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('highest_degree', sa.String(), nullable=True),
    sa.Column('field_of_study', sa.String(), nullable=True),
    sa.Column('gpa', sa.Float(), nullable=True),
    sa.Column('gre_score', sa.Integer(), nullable=True),
    sa.Column('toefl_score', sa.Integer(), nullable=True),
    sa.Column('ielts_score', sa.Float(), nullable=True),
    sa.Column('preferred_countries', sa.JSON(), nullable=True),
    sa.Column('preferred_programs', sa.JSON(), nullable=True),
    sa.Column('budget_range', sa.String(), nullable=True),
    sa.Column('work_experience_years', sa.Integer(), nullable=True),
    sa.Column('research_experience', sa.Text(), nullable=True),
    sa.Column('extracurriculars', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_applications_id'), table_name='applications')
    op.drop_table('applications')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_scholarships_scholarship_name'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_index(op.f('ix_scholarships_country'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_programs_university_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_program_name'), table_name='programs')
    op.drop_index(op.f('ix_programs_id'), table_name='programs')
    op.drop_index(op.f('ix_programs_field_of_study'), table_name='programs')
    op.drop_index(op.f('ix_programs_country'), table_name='programs')
    op.drop_table('programs')
    # ### end Alembic commands ###
